development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: postgres
  password: H0w6gra55!

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: postgres
  password: H0w6gra55!

